-- Supabase SQL Schema for Study Video Tracker
-- Note: NO date/timestamp fields as per project constraints.

create table if not exists users (
  id uuid primary key default gen_random_uuid(),
  email text unique not null,
  name text,
  image text,
  role text not null default 'viewer' check (role in ('uploader', 'viewer'))
);

create table if not exists videos (
  id bigint generated by default as identity primary key,
  title text not null,
  youtube_id text not null,
  tags text[] not null default '{}',
  category text,
  added_by uuid not null references users(id) on delete cascade
);

create table if not exists watched (
  user_id uuid not null references users(id) on delete cascade,
  video_id bigint not null references videos(id) on delete cascade,
  primary key (user_id, video_id)
);

-- How to promote a user to the "uploader" role manually:
-- UPDATE users SET role = 'uploader' WHERE email = 'user@example.com';
