-- Supabase SQL Schema for Study Video Tracker
-- Run this in your Supabase SQL Editor:

DROP TABLE IF EXISTS watched CASCADE;
DROP TABLE IF EXISTS videos CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id TEXT PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  name TEXT,
  image TEXT,
  role TEXT NOT NULL DEFAULT 'viewer'
);

CREATE TABLE videos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  subtitle TEXT,
  topic TEXT NOT NULL DEFAULT 'General',
  subtopic TEXT NOT NULL DEFAULT 'General Lessons',
  youtube_id TEXT NOT NULL,
  tags TEXT[] NOT NULL DEFAULT '{}',
  category TEXT,
  added_by TEXT NOT NULL
);

CREATE TABLE watched (
  user_id TEXT NOT NULL,
  video_id BIGINT NOT NULL,
  PRIMARY KEY (user_id, video_id)
);

-- Disable Row-Level Security so your backend and all users can sync videos
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE videos DISABLE ROW LEVEL SECURITY;
ALTER TABLE watched DISABLE ROW LEVEL SECURITY;
